/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calendariomaya.gui.nahual;

import calendariomaya.backend.manejadores.ManejadorCalcularFechaCholquij;
import calendariomaya.backend.manejadores.ManejadorCalcularNahuales;
import calendariomaya.backend.modelos.NahualDb;
import calendariomaya.backend.objetos.Nahual;
import calendariomaya.source.TextPrompt;
import java.awt.Frame;
import java.util.List;
import javax.swing.text.JTextComponent;

/**
 *
 * @author bryangmz
 */
public class CalcularNahual extends javax.swing.JDialog {

    private static CalcularNahual instancia;
    private List<Nahual> listaDeNahuales;
    private int index;
    
    /**
     * Creates new form AgregarEvento
     */
    private CalcularNahual(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static CalcularNahual getInstancia(Frame frame){
        if (instancia == null) {
            instancia = new CalcularNahual(frame, true);
        }   return instancia;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo1 = new javax.swing.JTextField();
        panelFechaCholquij = new javax.swing.JPanel();
        lblTituloNahuales = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        dateChoser = new com.toedter.calendar.JDateChooser();
        lblCalcularNahual = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        lblSiguiente = new javax.swing.JLabel();
        lblNombreNahual = new javax.swing.JLabel();
        lblNahualActual = new javax.swing.JLabel();
        lblAtras = new javax.swing.JLabel();
        lblNahualAnterior = new javax.swing.JLabel();
        lblNahualSiguiente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPaneSignificado = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPaneDescripcion = new javax.swing.JTextPane();

        txtTitulo1.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        txtTitulo1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        panelFechaCholquij.setBackground(new java.awt.Color(51, 51, 51));

        lblTituloNahuales.setFont(new java.awt.Font("Caviar Dreams", 1, 36)); // NOI18N
        lblTituloNahuales.setForeground(new java.awt.Color(204, 204, 204));
        lblTituloNahuales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloNahuales.setText("Nahuales");

        lblFecha.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(204, 204, 204));
        lblFecha.setText("Fecha*:");

        dateChoser.setBackground(new java.awt.Color(58, 63, 63));
        dateChoser.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        dateChoser.setForeground(new java.awt.Color(255, 255, 255));
        dateChoser.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N

        lblCalcularNahual.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblCalcularNahual.setForeground(new java.awt.Color(204, 204, 204));
        lblCalcularNahual.setText("Buscar Nahual");
        lblCalcularNahual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCalcularNahualMouseClicked(evt);
            }
        });

        lblDia.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblDia.setForeground(new java.awt.Color(204, 204, 204));
        lblDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDia.setText("Significado");

        lblMes.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblMes.setForeground(new java.awt.Color(204, 204, 204));
        lblMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMes.setText("Descripción");

        lblSiguiente.setFont(new java.awt.Font("Zekton", 1, 48)); // NOI18N
        lblSiguiente.setForeground(new java.awt.Color(204, 204, 204));
        lblSiguiente.setText(">");
        lblSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSiguienteMouseClicked(evt);
            }
        });

        lblNombreNahual.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblNombreNahual.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreNahual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreNahual.setText("Nahual");

        lblNahualActual.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblNahualActual.setForeground(new java.awt.Color(204, 204, 204));
        lblNahualActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblAtras.setFont(new java.awt.Font("Zekton", 1, 48)); // NOI18N
        lblAtras.setForeground(new java.awt.Color(204, 204, 204));
        lblAtras.setText("<");
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
        });

        lblNahualAnterior.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblNahualAnterior.setForeground(new java.awt.Color(204, 204, 204));
        lblNahualAnterior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblNahualSiguiente.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblNahualSiguiente.setForeground(new java.awt.Color(204, 204, 204));
        lblNahualSiguiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtPaneSignificado.setEditable(false);
        txtPaneSignificado.setBackground(new java.awt.Color(51, 51, 51));
        txtPaneSignificado.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtPaneSignificado.setFont(new java.awt.Font("Caviar Dreams", 0, 18)); // NOI18N
        txtPaneSignificado.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(txtPaneSignificado);

        txtPaneDescripcion.setEditable(false);
        txtPaneDescripcion.setBackground(new java.awt.Color(51, 51, 51));
        txtPaneDescripcion.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtPaneDescripcion.setFont(new java.awt.Font("Caviar Dreams", 1, 16)); // NOI18N
        txtPaneDescripcion.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(txtPaneDescripcion);

        javax.swing.GroupLayout panelFechaCholquijLayout = new javax.swing.GroupLayout(panelFechaCholquij);
        panelFechaCholquij.setLayout(panelFechaCholquijLayout);
        panelFechaCholquijLayout.setHorizontalGroup(
            panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFechaCholquijLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNahualAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblNahualActual, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblNahualSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblSiguiente)
                .addGap(27, 27, 27))
            .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                        .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 9, Short.MAX_VALUE))
                            .addComponent(lblTituloNahuales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombreNahual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFechaCholquijLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFecha)
                .addGap(18, 18, 18)
                .addComponent(dateChoser, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCalcularNahual)
                .addGap(122, 122, 122))
        );
        panelFechaCholquijLayout.setVerticalGroup(
            panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTituloNahuales)
                .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(lblAtras))
                    .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFecha)
                            .addComponent(dateChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCalcularNahual))
                        .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblNombreNahual)
                                .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(lblNahualActual, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(lblNahualSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(lblSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(lblNahualAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(lblDia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFechaCholquij, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFechaCholquij, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSiguienteMouseClicked
        // TODO add your handling code here:
        if(verificarNahuales()){
            siguiente();
            ManejadorCalcularNahuales.getInstancia().pintarNahuales(index, listaDeNahuales, lblNahualAnterior, lblNahualSiguiente, lblNahualActual, txtPaneDescripcion, txtPaneSignificado, lblNombreNahual);
            dateChoser.setDate(null);
        }
    }//GEN-LAST:event_lblSiguienteMouseClicked

    private void lblCalcularNahualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCalcularNahualMouseClicked
        // TODO add your handling code here:
        index = ManejadorCalcularFechaCholquij.getInstancia().nahual(ManejadorCalcularFechaCholquij.getInstancia().timeCholqij(dateChoser.getCalendar().getTime().getTime()));
        ManejadorCalcularNahuales.getInstancia().pintarNahuales(index - 1, listaDeNahuales, lblNahualAnterior, lblNahualSiguiente, lblNahualActual, txtPaneDescripcion, txtPaneSignificado, lblNombreNahual);
    }//GEN-LAST:event_lblCalcularNahualMouseClicked

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        // TODO add your handling code here:
        if(verificarNahuales()){
            anterior();
            ManejadorCalcularNahuales.getInstancia().pintarNahuales(index, listaDeNahuales, lblNahualAnterior, lblNahualSiguiente, lblNahualActual, txtPaneDescripcion, txtPaneSignificado, lblNombreNahual);
            dateChoser.setDate(null);
        }
    }//GEN-LAST:event_lblAtrasMouseClicked

    private void anterior(){
        if(index == 0)
            index = listaDeNahuales.size()-1;
        else
            index--;
    }
    
    private void siguiente(){
        if(index == (listaDeNahuales.size()-1))
            index = 0;
        else
            index++;
    }
    
    private boolean verificarNahuales(){
        return listaDeNahuales != null && listaDeNahuales.size() > 2;
    }
    
    public final void addPlaceHolder(String txtPlaceHolder, JTextComponent textField){
        TextPrompt placeholder = new TextPrompt(" " + txtPlaceHolder, textField);
        placeholder.changeAlpha(0.50f);
    }
    
    public void mostrar(){
        dateChoser.setDate(null);
        lblNombreNahual.setText("Nahual");
        txtPaneDescripcion.setText("");
        txtPaneSignificado.setText("");
        addPlaceHolder(" Significado", txtPaneSignificado);
        addPlaceHolder(" Descripción", txtPaneDescripcion);
        this.listaDeNahuales = NahualDb.getInstancia().getNahuales();
        this.index = 0;
        if(verificarNahuales()){
            ManejadorCalcularNahuales.getInstancia().pintarNahuales(index, listaDeNahuales, lblNahualAnterior, lblNahualSiguiente, lblNahualActual, txtPaneDescripcion, txtPaneSignificado, lblNombreNahual);
        }
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateChoser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblCalcularNahual;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblNahualActual;
    private javax.swing.JLabel lblNahualAnterior;
    private javax.swing.JLabel lblNahualSiguiente;
    private javax.swing.JLabel lblNombreNahual;
    private javax.swing.JLabel lblSiguiente;
    private javax.swing.JLabel lblTituloNahuales;
    private javax.swing.JPanel panelFechaCholquij;
    private javax.swing.JTextPane txtPaneDescripcion;
    private javax.swing.JTextPane txtPaneSignificado;
    private javax.swing.JTextField txtTitulo1;
    // End of variables declaration//GEN-END:variables
}
