/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calendariomaya.gui.rueda_calendarica.menu;


import calendariomaya.backend.manejadores.ManejadorCalcularFechaHabb;
import calendariomaya.backend.modelos.Utilidades;
import calendariomaya.source.TextPrompt;
import java.awt.Frame;
import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author bryangmz
 */
public class Correlacion extends javax.swing.JDialog {

    private static Correlacion instancia;
    
    /**
     * Creates new form AgregarEvento
     */
    private Correlacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static Correlacion getInstancia(Frame frame){
        if (instancia == null) {
            instancia = new Correlacion(frame, true);
        }   return instancia;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo1 = new javax.swing.JTextField();
        panelFechaCholquij = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblInformacion = new javax.swing.JLabel();
        lblInformacion1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        txtTitulo1.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        txtTitulo1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        panelFechaCholquij.setBackground(new java.awt.Color(51, 51, 51));

        lblTitulo.setFont(new java.awt.Font("Caviar Dreams", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 204, 204));
        lblTitulo.setText("Correlación mexica de los años");

        lblInformacion.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblInformacion.setForeground(new java.awt.Color(204, 204, 204));
        lblInformacion.setText("La siguiente tabla muestra la correspondencia del último");

        lblInformacion1.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblInformacion1.setForeground(new java.awt.Color(204, 204, 204));
        lblInformacion1.setText("periodo de 52 años entre los años mexicas y nuestros años: ");

        tabla.setBackground(new java.awt.Color(51, 51, 51));
        tabla.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tabla.setFont(new java.awt.Font("Caviar Dreams", 0, 16)); // NOI18N
        tabla.setForeground(new java.awt.Color(204, 204, 204));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "null", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tabla.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(2).setResizable(false);
            tabla.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout panelFechaCholquijLayout = new javax.swing.GroupLayout(panelFechaCholquij);
        panelFechaCholquij.setLayout(panelFechaCholquijLayout);
        panelFechaCholquijLayout.setHorizontalGroup(
            panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblInformacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelFechaCholquijLayout.setVerticalGroup(
            panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblInformacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInformacion1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFechaCholquij, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFechaCholquij, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final void addPlaceHolder(String txtPlaceHolder, JTextComponent textField){
        TextPrompt placeholder = new TextPrompt(" " + txtPlaceHolder, textField);
        placeholder.changeAlpha(0.50f);
    }
    
    public void mostrar(){
        agregarModel();
        this.setVisible(true);
    }
    
    public void agregarModel(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tlalpilli Tochtli");
        model.addColumn("Tlalpilli Acatl");
        model.addColumn("Tlalpilli Tecpatl");
        model.addColumn("Tlalpilli Calli");
        model.addRow(new Object[]{"1 tochtli / 1974", "1 acatl / 1987", "1 tecpatl / 2000", "1 calli / 2013"});
        model.addRow(new Object[]{"2 acatl / 1975", "2 tecpatl / 1988", "2 calli / 2001", "2 tochtli / 2014"});
        model.addRow(new Object[]{"3 tecpatl / 1976", "3 calli / 1989", "3 tochtli / 2002", "3 acatl / 2015"});
        model.addRow(new Object[]{"4 calli / 1977", "4 tochtli / 1990", "4 acatl / 2003", "4 tecpatl / 2016"});
        model.addRow(new Object[]{"5 tochtli / 1978", "5 acatl / 1991", "5 tecpatl / 2004", "5 calli / 2017"});
        model.addRow(new Object[]{"6 acatl / 1979", "6 tecpatl / 1992", "6 calli / 2005", "6 tochtli / 2018"});
        model.addRow(new Object[]{"7 tecpatl / 1980", "7 calli / 1993", "7 tochtli / 2006", "7 acatl / 2019"});
        model.addRow(new Object[]{"8 calli / 1981", "8 tochtli / 1994", "8 acatl / 2007", "8 tecpatl / 2020"});
        model.addRow(new Object[]{"9 tochtli / 1982", "9 acatl / 1995", "9 tecpatl / 2008", "9 calli / 2021"});
        model.addRow(new Object[]{"10 acatl / 1983", "10 tecpatl / 1996", "10 calli / 2009", "10 tochtli / 2022"});
        model.addRow(new Object[]{"11 tecpatl / 1984", "11 calli / 1997", "11 tochtli / 2010", "11 acatl / 2023"});
        model.addRow(new Object[]{"12 calli / 1985", "12 tochtli / 1998", "12 acatl / 2011", "12 tecpatl / 2024"});
        model.addRow(new Object[]{"13 tochtli / 1986", "13 acatl / 1999", "13 tecpatl / 2012", "13 calli / 2025"});
        tabla.setModel(model );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblInformacion1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelFechaCholquij;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtTitulo1;
    // End of variables declaration//GEN-END:variables
}
