/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calendariomaya.gui.cholquij.calcular_fecha;

import calendariomaya.backend.manejadores.ManejadorCalcularFechaCholquij;
import calendariomaya.gui.linea_de_tiempo.*;
import calendariomaya.backend.modelos.HechoHistoricoDb;
import calendariomaya.backend.modelos.Mensaje;
import calendariomaya.backend.modelos.Utilidades;
import calendariomaya.backend.objetos.HechoHistorico;
import calendariomaya.source.TextPrompt;
import java.awt.Color;
import java.awt.Frame;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.text.JTextComponent;

/**
 *
 * @author bryangmz
 */
public class CalcularFecha extends javax.swing.JDialog {

    private static CalcularFecha instancia;
    
    /**
     * Creates new form AgregarEvento
     */
    private CalcularFecha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static CalcularFecha getInstancia(Frame frame){
        if (instancia == null) {
            instancia = new CalcularFecha(frame, true);
        }   return instancia;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo1 = new javax.swing.JTextField();
        panelFechaCholquij = new javax.swing.JPanel();
        lblCalcularFecha = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        dateChoser = new com.toedter.calendar.JDateChooser();
        lblCalcular = new javax.swing.JLabel();
        lblCholquij = new javax.swing.JLabel();
        lblEnergia = new javax.swing.JLabel();
        lblImgEnergia = new javax.swing.JLabel();
        lblImgCholquij = new javax.swing.JLabel();

        txtTitulo1.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        txtTitulo1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        setResizable(false);

        panelFechaCholquij.setBackground(new java.awt.Color(51, 51, 51));

        lblCalcularFecha.setFont(new java.awt.Font("Caviar Dreams", 1, 36)); // NOI18N
        lblCalcularFecha.setForeground(new java.awt.Color(204, 204, 204));
        lblCalcularFecha.setText("Calcular Fecha");

        lblFecha.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(204, 204, 204));
        lblFecha.setText("Fecha*:");

        dateChoser.setBackground(new java.awt.Color(58, 63, 63));
        dateChoser.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        dateChoser.setForeground(new java.awt.Color(255, 255, 255));
        dateChoser.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N

        lblCalcular.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblCalcular.setForeground(new java.awt.Color(204, 204, 204));
        lblCalcular.setText("Calcular");
        lblCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCalcularMouseClicked(evt);
            }
        });

        lblCholquij.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblCholquij.setForeground(new java.awt.Color(204, 204, 204));
        lblCholquij.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCholquij.setText("Nahual");

        lblEnergia.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblEnergia.setForeground(new java.awt.Color(204, 204, 204));
        lblEnergia.setText("Energía");

        lblImgEnergia.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblImgEnergia.setForeground(new java.awt.Color(204, 204, 204));
        lblImgEnergia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblImgCholquij.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblImgCholquij.setForeground(new java.awt.Color(204, 204, 204));
        lblImgCholquij.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelFechaCholquijLayout = new javax.swing.GroupLayout(panelFechaCholquij);
        panelFechaCholquij.setLayout(panelFechaCholquijLayout);
        panelFechaCholquijLayout.setHorizontalGroup(
            panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lblCalcularFecha))
                    .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblImgCholquij, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImgEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lblEnergia))
                    .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCholquij, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                                .addComponent(lblFecha)
                                .addGap(18, 18, 18)
                                .addComponent(dateChoser, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCalcular)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelFechaCholquijLayout.setVerticalGroup(
            panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblCalcularFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFecha)
                    .addComponent(dateChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCalcular))
                .addGap(18, 18, 18)
                .addComponent(lblCholquij)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImgCholquij, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblEnergia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblImgEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFechaCholquij, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFechaCholquij, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCalcularMouseClicked
        // TODO add your handling code here:
        calcular();
    }//GEN-LAST:event_lblCalcularMouseClicked

    public void calcular(){
        if (dateChoser.getDate() != null) {
            lblImgCholquij.setIcon(ManejadorCalcularFechaCholquij.getInstancia().getIcon(ManejadorCalcularFechaCholquij.getInstancia().nahual(ManejadorCalcularFechaCholquij.getInstancia().timeCholqij(dateChoser.getCalendar().getTime().getTime()))));
            lblImgEnergia.setIcon(ManejadorCalcularFechaCholquij.getInstancia().getIconLvl(ManejadorCalcularFechaCholquij.getInstancia().nivel(ManejadorCalcularFechaCholquij.getInstancia().timeCholqij(dateChoser.getCalendar().getTime().getTime()))));
        } else {
            Mensaje.getInstancia().error("Debes de seleccionar una fecha.");
        }
    }
    
    public final void addPlaceHolder(String txtPlaceHolder, JTextComponent textField){
        TextPrompt placeholder = new TextPrompt(" " + txtPlaceHolder, textField);
        placeholder.changeAlpha(0.50f);
    }
    
    public void mostrar(){
        dateChoser.setDate(new java.util.Date());
        lblImgCholquij.setIcon(null);
        lblImgEnergia.setIcon(null);
        calcular();
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateChoser;
    private javax.swing.JLabel lblCalcular;
    private javax.swing.JLabel lblCalcularFecha;
    private javax.swing.JLabel lblCholquij;
    private javax.swing.JLabel lblEnergia;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblImgCholquij;
    private javax.swing.JLabel lblImgEnergia;
    private javax.swing.JPanel panelFechaCholquij;
    private javax.swing.JTextField txtTitulo1;
    // End of variables declaration//GEN-END:variables
}
