/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calendariomaya.gui.rueda_calendarica.calcular;

import calendariomaya.gui.habb.calcular_fecha.*;
import calendariomaya.backend.manejadores.ManejadorCalcularFechaCholquij;
import calendariomaya.backend.manejadores.ManejadorCalcularFechaHabb;
import calendariomaya.backend.modelos.Mensaje;
import calendariomaya.backend.modelos.Utilidades;
import calendariomaya.source.TextPrompt;
import java.awt.Frame;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.text.JTextComponent;

/**
 *
 * @author bryangmz
 */
public class CalcularFechaRC extends javax.swing.JDialog {

    private static CalcularFechaRC instancia;
    
    /**
     * Creates new form AgregarEvento
     */
    private CalcularFechaRC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static CalcularFechaRC getInstancia(Frame frame){
        if (instancia == null) {
            instancia = new CalcularFechaRC(frame, true);
        }   return instancia;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo1 = new javax.swing.JTextField();
        panelFechaCholquij = new javax.swing.JPanel();
        lblCalcularFecha = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        dateChoser = new com.toedter.calendar.JDateChooser();
        lblBuscar = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        lblImgMes = new javax.swing.JLabel();
        lblImgDia = new javax.swing.JLabel();
        lblSiguienteDia = new javax.swing.JLabel();
        lblAtrasDia = new javax.swing.JLabel();
        lblAtrasMes = new javax.swing.JLabel();
        lblSiguienteMes = new javax.swing.JLabel();
        lblCargador = new javax.swing.JLabel();
        lblImgEnergia = new javax.swing.JLabel();
        lblDia1 = new javax.swing.JLabel();
        lblMes1 = new javax.swing.JLabel();
        lblImgCholquij = new javax.swing.JLabel();

        txtTitulo1.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        txtTitulo1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        panelFechaCholquij.setBackground(new java.awt.Color(51, 51, 51));

        lblCalcularFecha.setFont(new java.awt.Font("Caviar Dreams", 1, 36)); // NOI18N
        lblCalcularFecha.setForeground(new java.awt.Color(204, 204, 204));
        lblCalcularFecha.setText("Calcular Fecha");

        lblFecha.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(204, 204, 204));
        lblFecha.setText("Fecha*:");

        dateChoser.setBackground(new java.awt.Color(58, 63, 63));
        dateChoser.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        dateChoser.setForeground(new java.awt.Color(255, 255, 255));
        dateChoser.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N

        lblBuscar.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(204, 204, 204));
        lblBuscar.setText("Buscar");
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarMouseClicked(evt);
            }
        });

        lblDia.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblDia.setForeground(new java.awt.Color(204, 204, 204));
        lblDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDia.setText("Día");

        lblMes.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblMes.setForeground(new java.awt.Color(204, 204, 204));
        lblMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMes.setText("Mes");

        lblImgMes.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblImgMes.setForeground(new java.awt.Color(204, 204, 204));
        lblImgMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblImgDia.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblImgDia.setForeground(new java.awt.Color(204, 204, 204));
        lblImgDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblSiguienteDia.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        lblSiguienteDia.setForeground(new java.awt.Color(204, 204, 204));
        lblSiguienteDia.setText(">");
        lblSiguienteDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSiguienteDiaMouseClicked(evt);
            }
        });

        lblAtrasDia.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        lblAtrasDia.setForeground(new java.awt.Color(204, 204, 204));
        lblAtrasDia.setText("<");
        lblAtrasDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasDiaMouseClicked(evt);
            }
        });

        lblAtrasMes.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        lblAtrasMes.setForeground(new java.awt.Color(204, 204, 204));
        lblAtrasMes.setText("<");
        lblAtrasMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMesMouseClicked(evt);
            }
        });

        lblSiguienteMes.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        lblSiguienteMes.setForeground(new java.awt.Color(204, 204, 204));
        lblSiguienteMes.setText(">");
        lblSiguienteMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSiguienteMesMouseClicked(evt);
            }
        });

        lblCargador.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblCargador.setForeground(new java.awt.Color(204, 204, 204));
        lblCargador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCargador.setText("Rueda Calendarica");

        lblImgEnergia.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblImgEnergia.setForeground(new java.awt.Color(204, 204, 204));
        lblImgEnergia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblDia1.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblDia1.setForeground(new java.awt.Color(204, 204, 204));
        lblDia1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDia1.setText("Nahual");

        lblMes1.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblMes1.setForeground(new java.awt.Color(204, 204, 204));
        lblMes1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMes1.setText("Energía");

        lblImgCholquij.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblImgCholquij.setForeground(new java.awt.Color(204, 204, 204));
        lblImgCholquij.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelFechaCholquijLayout = new javax.swing.GroupLayout(panelFechaCholquij);
        panelFechaCholquij.setLayout(panelFechaCholquijLayout);
        panelFechaCholquijLayout.setHorizontalGroup(
            panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                        .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                                    .addGap(66, 66, 66)
                                    .addComponent(lblCalcularFecha))
                                .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(lblFecha)
                                    .addGap(18, 18, 18)
                                    .addComponent(dateChoser, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblBuscar)))
                            .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblCargador, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lblImgDia, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                                .addComponent(lblImgMes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(lblAtrasDia)
                                .addGap(18, 18, 18)
                                .addComponent(lblSiguienteDia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAtrasMes)
                                .addGap(18, 18, 18)
                                .addComponent(lblSiguienteMes)
                                .addGap(70, 70, 70))
                            .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                                .addComponent(lblDia, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFechaCholquijLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblDia1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMes1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFechaCholquijLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblImgCholquij, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImgEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        panelFechaCholquijLayout.setVerticalGroup(
            panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaCholquijLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblCalcularFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFecha)
                    .addComponent(dateChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCargador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMes1)
                    .addComponent(lblDia1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImgEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImgCholquij, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMes)
                    .addComponent(lblDia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImgDia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImgMes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFechaCholquijLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSiguienteDia)
                        .addComponent(lblAtrasDia)
                        .addComponent(lblSiguienteMes))
                    .addComponent(lblAtrasMes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFechaCholquij, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFechaCholquij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSiguienteMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSiguienteMesMouseClicked
        // TODO add your handling code here:
        dateChoser.setDate(ManejadorCalcularFechaHabb.getInstancia().mesSiguiente(dateChoser.getDate()));
        calcularCholquij();
        calcularHaab();
    }//GEN-LAST:event_lblSiguienteMesMouseClicked

    private void lblAtrasMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMesMouseClicked
        // TODO add your handling code here:
        dateChoser.setDate(ManejadorCalcularFechaHabb.getInstancia().mesAnterior(dateChoser.getDate()));
        calcularCholquij();
        calcularHaab();
    }//GEN-LAST:event_lblAtrasMesMouseClicked

    private void lblAtrasDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasDiaMouseClicked
        // TODO add your handling code here:
        dateChoser.setDate(ManejadorCalcularFechaHabb.getInstancia().fechaAnterior(dateChoser.getDate()));
        calcularCholquij();
        calcularHaab();
    }//GEN-LAST:event_lblAtrasDiaMouseClicked

    private void lblSiguienteDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSiguienteDiaMouseClicked
        // TODO add your handling code here:
        dateChoser.setDate(ManejadorCalcularFechaHabb.getInstancia().fechaSiguiente(dateChoser.getDate()));
        calcularCholquij();
        calcularHaab();
    }//GEN-LAST:event_lblSiguienteDiaMouseClicked

    private void lblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseClicked
        // TODO add your handling code here:
        if (dateChoser.getDate() != null) {
            calcularCholquij();
            calcularHaab();
        } else {
            Mensaje.getInstancia().error("Debes de seleccionar una fecha.");
        }
    }//GEN-LAST:event_lblBuscarMouseClicked

    public final void addPlaceHolder(String txtPlaceHolder, JTextComponent textField){
        TextPrompt placeholder = new TextPrompt(" " + txtPlaceHolder, textField);
        placeholder.changeAlpha(0.50f);
    }
    
    public void calcularHaab(){
        ManejadorCalcularFechaHabb.getInstancia().escribirFechaRuedaCalendarica(lblDia, lblMes, lblImgDia, lblImgMes, dateChoser.getDate());
    }
    
    public void calcularCholquij(){
        if (dateChoser.getDate() != null) {
            lblImgCholquij.setIcon(ManejadorCalcularFechaCholquij.getInstancia().getIcon(ManejadorCalcularFechaCholquij.getInstancia().nahual(ManejadorCalcularFechaCholquij.getInstancia().timeCholqij(dateChoser.getCalendar().getTime().getTime()))));
            lblImgEnergia.setIcon(ManejadorCalcularFechaCholquij.getInstancia().getIconLvl(ManejadorCalcularFechaCholquij.getInstancia().nivel(ManejadorCalcularFechaCholquij.getInstancia().timeCholqij(dateChoser.getCalendar().getTime().getTime()))));
        } else {
            Mensaje.getInstancia().error("Debes de seleccionar una fecha.");
        }
    }
    
    public void mostrar(){
        dateChoser.setDate(new Date());
        calcularCholquij();
        calcularHaab();
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateChoser;
    private javax.swing.JLabel lblAtrasDia;
    private javax.swing.JLabel lblAtrasMes;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCalcularFecha;
    private javax.swing.JLabel lblCargador;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblDia1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblImgCholquij;
    private javax.swing.JLabel lblImgDia;
    private javax.swing.JLabel lblImgEnergia;
    private javax.swing.JLabel lblImgMes;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblMes1;
    private javax.swing.JLabel lblSiguienteDia;
    private javax.swing.JLabel lblSiguienteMes;
    private javax.swing.JPanel panelFechaCholquij;
    private javax.swing.JTextField txtTitulo1;
    // End of variables declaration//GEN-END:variables
}
