/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calendariomaya.gui.menu;

import calendariomaya.backend.modelos.InformacionDb;
import calendariomaya.backend.modelos.Mensaje;
import calendariomaya.gui.perfil.inicio_sesion.InicioSesion;
import calendariomaya.gui.linea_de_tiempo.LineaDeTiempo;
import calendariomaya.gui.cholquij.menu.MenuCalendarioCholquij;
import calendariomaya.gui.habb.menu.MenuCalendarioHabb;
import calendariomaya.gui.nahual.CalcularNahual;
import calendariomaya.gui.perfil.Perfil;
import calendariomaya.gui.perfil.PerfilActual;
import calendariomaya.gui.rueda_calendarica.menu.MenuRuedaCalendarica;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author bryangmz
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private static MenuPrincipal instancia;
    
    /**
     * Creates new form MenuPrincipal
     */
    private MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static MenuPrincipal getInstancia(){
        if (instancia == null) {
            instancia = new MenuPrincipal();
        } return instancia;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarraMenu = new javax.swing.JPanel();
        lblLineaTiempo = new javax.swing.JLabel();
        lblCalendarioHabb = new javax.swing.JLabel();
        lblCalendarioCholquij = new javax.swing.JLabel();
        lblRuedaCalendarica = new javax.swing.JLabel();
        lblNahual = new javax.swing.JLabel();
        panelPerfil = new javax.swing.JPanel();
        lblPerfil = new javax.swing.JLabel();
        lblNombrePerfil = new javax.swing.JLabel();
        lblAcercaDe = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        lblTiempoMaya = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblMenuPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tiempo Maya");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarraMenu.setBackground(new Color(0,0,0,110));
        panelBarraMenu.setForeground(new Color(255,255,255,165));

        lblLineaTiempo.setBackground(new java.awt.Color(204, 204, 204));
        lblLineaTiempo.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        lblLineaTiempo.setForeground(new java.awt.Color(204, 204, 204));
        lblLineaTiempo.setText("Linea de Tiempo");
        lblLineaTiempo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLineaTiempoMouseClicked(evt);
            }
        });

        lblCalendarioHabb.setBackground(new java.awt.Color(204, 204, 204));
        lblCalendarioHabb.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        lblCalendarioHabb.setForeground(new java.awt.Color(204, 204, 204));
        lblCalendarioHabb.setText("Calendario Haab'");
        lblCalendarioHabb.setToolTipText("Calendario Haab'");
        lblCalendarioHabb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCalendarioHabbMouseClicked(evt);
            }
        });

        lblCalendarioCholquij.setBackground(new java.awt.Color(204, 204, 204));
        lblCalendarioCholquij.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        lblCalendarioCholquij.setForeground(new java.awt.Color(204, 204, 204));
        lblCalendarioCholquij.setText("Calendario Cholq'ij");
        lblCalendarioCholquij.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCalendarioCholquijMouseClicked(evt);
            }
        });

        lblRuedaCalendarica.setBackground(new java.awt.Color(204, 204, 204));
        lblRuedaCalendarica.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        lblRuedaCalendarica.setForeground(new java.awt.Color(204, 204, 204));
        lblRuedaCalendarica.setText("Rueda Calendarica");
        lblRuedaCalendarica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRuedaCalendaricaMouseClicked(evt);
            }
        });

        lblNahual.setBackground(new java.awt.Color(204, 204, 204));
        lblNahual.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        lblNahual.setForeground(new java.awt.Color(204, 204, 204));
        lblNahual.setText("Nahual");
        lblNahual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNahualMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBarraMenuLayout = new javax.swing.GroupLayout(panelBarraMenu);
        panelBarraMenu.setLayout(panelBarraMenuLayout);
        panelBarraMenuLayout.setHorizontalGroup(
            panelBarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblLineaTiempo)
                .addGap(18, 18, 18)
                .addComponent(lblCalendarioHabb)
                .addGap(12, 12, 12)
                .addComponent(lblCalendarioCholquij)
                .addGap(18, 18, 18)
                .addComponent(lblRuedaCalendarica)
                .addGap(18, 18, 18)
                .addComponent(lblNahual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBarraMenuLayout.setVerticalGroup(
            panelBarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblLineaTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(lblCalendarioHabb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCalendarioCholquij, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRuedaCalendarica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNahual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelBarraMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 50));

        panelPerfil.setBackground(new Color(0,0,0,100));

        lblPerfil.setBackground(new java.awt.Color(204, 204, 204));
        lblPerfil.setFont(new java.awt.Font("AvantGarde LT Medium", 0, 16)); // NOI18N
        lblPerfil.setForeground(new java.awt.Color(204, 204, 204));
        lblPerfil.setText("Perfil");
        lblPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPerfilMouseClicked(evt);
            }
        });

        lblNombrePerfil.setBackground(new java.awt.Color(204, 204, 204));
        lblNombrePerfil.setFont(new java.awt.Font("AvantGarde LT Medium", 0, 16)); // NOI18N
        lblNombrePerfil.setForeground(new java.awt.Color(204, 204, 204));

        lblAcercaDe.setBackground(new java.awt.Color(204, 204, 204));
        lblAcercaDe.setFont(new java.awt.Font("AvantGarde LT Medium", 0, 16)); // NOI18N
        lblAcercaDe.setForeground(new java.awt.Color(204, 204, 204));
        lblAcercaDe.setText("Acerca de...");
        lblAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAcercaDeMouseClicked(evt);
            }
        });

        lblCerrarSesion.setBackground(new java.awt.Color(204, 204, 204));
        lblCerrarSesion.setFont(new java.awt.Font("AvantGarde LT Medium", 0, 16)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(204, 204, 204));
        lblCerrarSesion.setText("Cerrar Sesion");
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
        });

        lblTiempoMaya.setBackground(new java.awt.Color(204, 204, 204));
        lblTiempoMaya.setFont(new java.awt.Font("AvantGarde LT Medium", 0, 16)); // NOI18N
        lblTiempoMaya.setForeground(new java.awt.Color(204, 204, 204));
        lblTiempoMaya.setText("Tiempo Maya");

        javax.swing.GroupLayout panelPerfilLayout = new javax.swing.GroupLayout(panelPerfil);
        panelPerfil.setLayout(panelPerfilLayout);
        panelPerfilLayout.setHorizontalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPerfilLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTiempoMaya)
                    .addComponent(lblNombrePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCerrarSesion)
                    .addGroup(panelPerfilLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblAcercaDe)))
                .addGap(15, 15, 15))
            .addGroup(panelPerfilLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblPerfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPerfilLayout.setVerticalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPerfilLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblTiempoMaya)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombrePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCerrarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAcercaDe)
                .addGap(21, 21, 21))
        );

        getContentPane().add(panelPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 490, 150, 180));

        jLabel2.setFont(new java.awt.Font("AvantGarde LT Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("© 2021 Calendario Maya.  Todos los derechos reservados.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, 570, 20));

        lblMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendariomaya/img/MenuPrincipal.jpg"))); // NOI18N
        getContentPane().add(lblMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPerfilMouseClicked
        // TODO add your handling code here:
        Perfil.getInstancia(this).mostrarPerfil();
    }//GEN-LAST:event_lblPerfilMouseClicked

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por utilizar esta aplicaión!");
        this.setVisible(false);
        PerfilActual.getPerfilActual().cerrarSesion();
        Inicio.getInstancia().setVisible(true);
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void lblLineaTiempoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLineaTiempoMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        LineaDeTiempo.getInstancia().mostarLineaDeTiempo();
    }//GEN-LAST:event_lblLineaTiempoMouseClicked

    private void lblCalendarioCholquijMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCalendarioCholquijMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        MenuCalendarioCholquij.getInstancia().mostarMenuPrincipal();
    }//GEN-LAST:event_lblCalendarioCholquijMouseClicked

    private void lblCalendarioHabbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCalendarioHabbMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        MenuCalendarioHabb.getInstancia().mostarMenuPrincipal();
    }//GEN-LAST:event_lblCalendarioHabbMouseClicked

    private void lblAcercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcercaDeMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, InformacionDb.getInstancia().getInformacion("inf_acerca_de").getDescripcionEscritorio(), "Acerca de...", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lblAcercaDeMouseClicked

    private void lblNahualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNahualMouseClicked
        // TODO add your handling code here:
        CalcularNahual.getInstancia(this).mostrar();
    }//GEN-LAST:event_lblNahualMouseClicked

    private void lblRuedaCalendaricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRuedaCalendaricaMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        MenuRuedaCalendarica.getInstancia().mostarMenuPrincipal();
    }//GEN-LAST:event_lblRuedaCalendaricaMouseClicked

    public void mostarMenuPrincipal(){
        if (PerfilActual.getPerfilActual().sesionActiva()) {
            this.setVisible(true);
            lblNombrePerfil.setText(PerfilActual.getPerfilActual().getNomreUsuario());
        } else {
            this.setVisible(false);
            Mensaje.getInstancia().error("Debes de iniciar sesión");
            InicioSesion.getInstancia().mostrarInicioSesion();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAcercaDe;
    private javax.swing.JLabel lblCalendarioCholquij;
    private javax.swing.JLabel lblCalendarioHabb;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblLineaTiempo;
    private javax.swing.JLabel lblMenuPrincipal;
    private javax.swing.JLabel lblNahual;
    private javax.swing.JLabel lblNombrePerfil;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblRuedaCalendarica;
    private javax.swing.JLabel lblTiempoMaya;
    private javax.swing.JPanel panelBarraMenu;
    private javax.swing.JPanel panelPerfil;
    // End of variables declaration//GEN-END:variables
}
