/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calendariomaya.gui.linea_de_tiempo;

import calendariomaya.backend.modelos.HechoHistoricoDb;
import calendariomaya.backend.modelos.Mensaje;
import calendariomaya.backend.objetos.HechoHistorico;
import calendariomaya.source.TextPrompt;
import java.awt.Color;
import java.awt.Frame;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.text.JTextComponent;

/**
 *
 * @author bryangmz
 */
public class AgregarEvento extends javax.swing.JDialog {

    private static AgregarEvento instancia;
    
    /**
     * Creates new form AgregarEvento
     */
    private AgregarEvento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static AgregarEvento getInstancia(Frame frame){
        if (instancia == null) {
            instancia = new AgregarEvento(frame, true);
        }   return instancia;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo1 = new javax.swing.JTextField();
        panelAgregarEvento = new javax.swing.JPanel();
        lblEvento = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        lblFin = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtTitulo = new javax.swing.JTextField();
        txtInicio = new javax.swing.JTextField();
        txtFinal = new javax.swing.JTextField();
        lblAgregar = new javax.swing.JLabel();

        txtTitulo1.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        txtTitulo1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        panelAgregarEvento.setBackground(new java.awt.Color(51, 51, 51));

        lblEvento.setFont(new java.awt.Font("Caviar Dreams", 1, 36)); // NOI18N
        lblEvento.setForeground(new java.awt.Color(204, 204, 204));
        lblEvento.setText("Evento");

        lblTitulo.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 204, 204));
        lblTitulo.setText("Título*:");

        lblInicio.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(204, 204, 204));
        lblInicio.setText("Año - Inicio*:");

        lblFin.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblFin.setForeground(new java.awt.Color(204, 204, 204));
        lblFin.setText("Año - Fin*:");

        lblDescripcion.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(204, 204, 204));
        lblDescripcion.setText("Descripción*:");

        txtDescripcion.setBackground(new java.awt.Color(51, 51, 51));
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Caviar Dreams", 0, 16)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jScrollPane1.setViewportView(txtDescripcion);

        txtTitulo.setBackground(new Color(0,0,0,175));
        txtTitulo.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        txtInicio.setBackground(new Color(0,0,0,175));
        txtInicio.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        txtInicio.setForeground(new java.awt.Color(255, 255, 255));
        txtInicio.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInicioKeyTyped(evt);
            }
        });

        txtFinal.setBackground(new Color(0,0,0,175));
        txtFinal.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        txtFinal.setForeground(new java.awt.Color(255, 255, 255));
        txtFinal.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFinalKeyTyped(evt);
            }
        });

        lblAgregar.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        lblAgregar.setForeground(new java.awt.Color(204, 204, 204));
        lblAgregar.setText("Agregar");
        lblAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarEventoLayout = new javax.swing.GroupLayout(panelAgregarEvento);
        panelAgregarEvento.setLayout(panelAgregarEventoLayout);
        panelAgregarEventoLayout.setHorizontalGroup(
            panelAgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarEventoLayout.createSequentialGroup()
                .addGroup(panelAgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarEventoLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(lblEvento))
                    .addGroup(panelAgregarEventoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panelAgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAgregarEventoLayout.createSequentialGroup()
                                    .addComponent(lblDescripcion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAgregar))
                                .addGroup(panelAgregarEventoLayout.createSequentialGroup()
                                    .addComponent(lblInicio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblFin)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAgregarEventoLayout.createSequentialGroup()
                                    .addComponent(lblTitulo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelAgregarEventoLayout.setVerticalGroup(
            panelAgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarEventoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblEvento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInicio)
                    .addComponent(lblFin)
                    .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(lblAgregar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAgregarEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAgregarEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInicioKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if (value <'0' || value >'9') evt.consume();
    }//GEN-LAST:event_txtInicioKeyTyped

    private void txtFinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFinalKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if (value <'0' || value >'9') evt.consume();
    }//GEN-LAST:event_txtFinalKeyTyped

    private void lblAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseClicked
        // TODO add your handling code here:        
        if (txtTitulo.getText().isEmpty() || txtInicio.getText().isEmpty() || txtFinal.getText().isEmpty() || txtDescripcion.getText().isEmpty()) {
            Mensaje.getInstancia().error("Evento no agregado todos los campos son obligatorios!");
        } else {
            HechoHistorico edt = new HechoHistorico(HechoHistoricoDb.getInstancia().leerHechosHistoricos().size() + 2, 
                    parseFecha(txtInicio.getText()), parseFecha(txtFinal.getText()), txtTitulo.getText(), txtDescripcion.getText());
            HechoHistoricoDb.getInstancia().crearHH(edt);
            LineaDeTiempo.getInstancia().obtenerHechos();
            Mensaje.getInstancia().informacion("Hecho Historico Agregado!");
            limpiarCampos();
        }
    }//GEN-LAST:event_lblAgregarMouseClicked

    public static Date parseFecha(String fecha){
        fecha = "3/1/" + fecha.replace(" ", "");
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaDate = null;
        try {
            fechaDate = new Date(formato.parse(fecha).getTime());
            System.out.println("Fecha: " + fecha);
            System.out.println("Fecha: " + fechaDate.toString());
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        return fechaDate;
    }
    
    public void limpiarCampos(){
        txtTitulo.setText("");
        txtInicio.setText("");
        txtFinal.setText("");
        txtDescripcion.setText("");
    }
    
    public final void addPlaceHolder(String txtPlaceHolder, JTextComponent textField){
        TextPrompt placeholder = new TextPrompt(" " + txtPlaceHolder, textField);
        placeholder.changeAlpha(0.50f);
    }
    
    public void init(){
        addPlaceHolder(" Título", txtTitulo);
        addPlaceHolder(" Año Inicial", txtInicio);
        addPlaceHolder(" Año Finalizo", txtFinal);
        addPlaceHolder(" Descripción", txtDescripcion);
    }
    
    public void mostrar(){
        limpiarCampos();
        init();
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEvento;
    private javax.swing.JLabel lblFin;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelAgregarEvento;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtFinal;
    private javax.swing.JTextField txtInicio;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTitulo1;
    // End of variables declaration//GEN-END:variables
}
