/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calendariomaya.gui.cholquij.menu;

import calendariomaya.backend.manejadores.ManejadorInformacionOptionPane;
import calendariomaya.backend.modelos.InformacionDb;
import calendariomaya.backend.modelos.Mensaje;
import calendariomaya.gui.cholquij.calcular_fecha.CalcularFecha;
import calendariomaya.gui.perfil.inicio_sesion.InicioSesion;
import calendariomaya.gui.linea_de_tiempo.LineaDeTiempo;
import calendariomaya.gui.menu.MenuPrincipal;
import calendariomaya.gui.perfil.Perfil;
import calendariomaya.gui.perfil.PerfilActual;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author bryangmz
 */
public class MenuCalendarioCholquij extends javax.swing.JFrame {

    private static MenuCalendarioCholquij instancia;
    
    /**
     * Creates new form MenuPrincipal
     */
    private MenuCalendarioCholquij() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static MenuCalendarioCholquij getInstancia(){
        if (instancia == null) {
            instancia = new MenuCalendarioCholquij();
        } return instancia;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarraMenu = new javax.swing.JPanel();
        lblCalendarioCholqij = new javax.swing.JLabel();
        lblCalendarioLunar = new javax.swing.JLabel();
        lblDias = new javax.swing.JLabel();
        lblFormasDeContar = new javax.swing.JLabel();
        lblConvertidorDeFechas = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        panelPerfil = new javax.swing.JPanel();
        lblPerfil = new javax.swing.JLabel();
        lblNombrePerfil = new javax.swing.JLabel();
        lblAcercaDe = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        lblTiempoMaya = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblMenuPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tiempo Maya");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarraMenu.setBackground(new Color(0,0,0,110));
        panelBarraMenu.setForeground(new Color(255,255,255,165));

        lblCalendarioCholqij.setBackground(new java.awt.Color(204, 204, 204));
        lblCalendarioCholqij.setFont(new java.awt.Font("Caviar Dreams", 1, 21)); // NOI18N
        lblCalendarioCholqij.setForeground(new java.awt.Color(204, 204, 204));
        lblCalendarioCholqij.setText("Calendario Cholq'ij");
        lblCalendarioCholqij.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCalendarioCholqijMouseClicked(evt);
            }
        });

        lblCalendarioLunar.setBackground(new java.awt.Color(204, 204, 204));
        lblCalendarioLunar.setFont(new java.awt.Font("Caviar Dreams", 1, 21)); // NOI18N
        lblCalendarioLunar.setForeground(new java.awt.Color(204, 204, 204));
        lblCalendarioLunar.setText("Calendario Lunar");
        lblCalendarioLunar.setToolTipText("Calendario Haab'");
        lblCalendarioLunar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCalendarioLunarMouseClicked(evt);
            }
        });

        lblDias.setBackground(new java.awt.Color(204, 204, 204));
        lblDias.setFont(new java.awt.Font("Caviar Dreams", 1, 21)); // NOI18N
        lblDias.setForeground(new java.awt.Color(204, 204, 204));
        lblDias.setText("Días");
        lblDias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDiasMouseClicked(evt);
            }
        });

        lblFormasDeContar.setBackground(new java.awt.Color(204, 204, 204));
        lblFormasDeContar.setFont(new java.awt.Font("Caviar Dreams", 1, 21)); // NOI18N
        lblFormasDeContar.setForeground(new java.awt.Color(204, 204, 204));
        lblFormasDeContar.setText("Formas de Contar");
        lblFormasDeContar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFormasDeContarMouseClicked(evt);
            }
        });

        lblConvertidorDeFechas.setBackground(new java.awt.Color(204, 204, 204));
        lblConvertidorDeFechas.setFont(new java.awt.Font("Caviar Dreams", 1, 21)); // NOI18N
        lblConvertidorDeFechas.setForeground(new java.awt.Color(204, 204, 204));
        lblConvertidorDeFechas.setText("Fecha Cholq'ij");
        lblConvertidorDeFechas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConvertidorDeFechasMouseClicked(evt);
            }
        });

        lblMenu.setBackground(new java.awt.Color(204, 204, 204));
        lblMenu.setFont(new java.awt.Font("Caviar Dreams", 1, 21)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(204, 204, 204));
        lblMenu.setText("Menú");
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBarraMenuLayout = new javax.swing.GroupLayout(panelBarraMenu);
        panelBarraMenu.setLayout(panelBarraMenuLayout);
        panelBarraMenuLayout.setHorizontalGroup(
            panelBarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraMenuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblCalendarioCholqij)
                .addGap(26, 26, 26)
                .addComponent(lblCalendarioLunar)
                .addGap(35, 35, 35)
                .addComponent(lblDias)
                .addGap(36, 36, 36)
                .addComponent(lblFormasDeContar)
                .addGap(35, 35, 35)
                .addComponent(lblConvertidorDeFechas)
                .addGap(32, 32, 32))
        );
        panelBarraMenuLayout.setVerticalGroup(
            panelBarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblCalendarioCholqij, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(lblCalendarioLunar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFormasDeContar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblConvertidorDeFechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelBarraMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 50));

        panelPerfil.setBackground(new Color(0,0,0,100));

        lblPerfil.setBackground(new java.awt.Color(204, 204, 204));
        lblPerfil.setFont(new java.awt.Font("AvantGarde LT Medium", 0, 16)); // NOI18N
        lblPerfil.setForeground(new java.awt.Color(204, 204, 204));
        lblPerfil.setText("Perfil");
        lblPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPerfilMouseClicked(evt);
            }
        });

        lblNombrePerfil.setBackground(new java.awt.Color(204, 204, 204));
        lblNombrePerfil.setFont(new java.awt.Font("AvantGarde LT Medium", 0, 16)); // NOI18N
        lblNombrePerfil.setForeground(new java.awt.Color(204, 204, 204));

        lblAcercaDe.setBackground(new java.awt.Color(204, 204, 204));
        lblAcercaDe.setFont(new java.awt.Font("AvantGarde LT Medium", 0, 16)); // NOI18N
        lblAcercaDe.setForeground(new java.awt.Color(204, 204, 204));
        lblAcercaDe.setText("Acerca de...");
        lblAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAcercaDeMouseClicked(evt);
            }
        });

        lblCerrarSesion.setBackground(new java.awt.Color(204, 204, 204));
        lblCerrarSesion.setFont(new java.awt.Font("AvantGarde LT Medium", 0, 16)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(204, 204, 204));
        lblCerrarSesion.setText("Cerrar Sesion");
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
        });

        lblTiempoMaya.setBackground(new java.awt.Color(204, 204, 204));
        lblTiempoMaya.setFont(new java.awt.Font("AvantGarde LT Medium", 0, 16)); // NOI18N
        lblTiempoMaya.setForeground(new java.awt.Color(204, 204, 204));
        lblTiempoMaya.setText("Tiempo Maya");

        javax.swing.GroupLayout panelPerfilLayout = new javax.swing.GroupLayout(panelPerfil);
        panelPerfil.setLayout(panelPerfilLayout);
        panelPerfilLayout.setHorizontalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPerfilLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTiempoMaya)
                    .addComponent(lblNombrePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCerrarSesion)
                    .addGroup(panelPerfilLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblAcercaDe)))
                .addGap(15, 15, 15))
            .addGroup(panelPerfilLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblPerfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPerfilLayout.setVerticalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPerfilLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblTiempoMaya)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombrePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCerrarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAcercaDe)
                .addGap(21, 21, 21))
        );

        getContentPane().add(panelPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 490, 150, 180));

        jLabel2.setFont(new java.awt.Font("AvantGarde LT Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("© 2021 Calendario Maya.  Todos los derechos reservados.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, 570, 20));

        lblMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendariomaya/img/MenuPrincipal.jpg"))); // NOI18N
        getContentPane().add(lblMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPerfilMouseClicked
        // TODO add your handling code here:
        Perfil.getInstancia(this).mostrarPerfil();
    }//GEN-LAST:event_lblPerfilMouseClicked

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por utilizar esta aplicaión!");
        this.setVisible(false);
        PerfilActual.getPerfilActual().cerrarSesion();
        InicioSesion.getInstancia().mostrarInicioSesion();
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void lblCalendarioCholqijMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCalendarioCholqijMouseClicked
        // TODO add your handling code here:
        ManejadorInformacionOptionPane.getInstancia().mostrarInfCholquij();
    }//GEN-LAST:event_lblCalendarioCholqijMouseClicked

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        MenuPrincipal.getInstancia().mostarMenuPrincipal();
    }//GEN-LAST:event_lblMenuMouseClicked

    private void lblCalendarioLunarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCalendarioLunarMouseClicked
        // TODO add your handling code here:
        ManejadorInformacionOptionPane.getInstancia().mostrarInfCalendarioLunar();
    }//GEN-LAST:event_lblCalendarioLunarMouseClicked

    private void lblDiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDiasMouseClicked
        // TODO add your handling code here:
        ManejadorInformacionOptionPane.getInstancia().mostrarInfDiasCholquij();
    }//GEN-LAST:event_lblDiasMouseClicked

    private void lblFormasDeContarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFormasDeContarMouseClicked
        // TODO add your handling code here:
        ManejadorInformacionOptionPane.getInstancia().mostarInfFormasDeContar();
    }//GEN-LAST:event_lblFormasDeContarMouseClicked

    private void lblConvertidorDeFechasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConvertidorDeFechasMouseClicked
        // TODO add your handling code here:
        CalcularFecha.getInstancia(this).mostrar();
    }//GEN-LAST:event_lblConvertidorDeFechasMouseClicked

    private void lblAcercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcercaDeMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, InformacionDb.getInstancia().getInformacion("inf_acerca_de").getDescripcionEscritorio(), "Acerca de...", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lblAcercaDeMouseClicked

    public void mostarMenuPrincipal(){
        if (PerfilActual.getPerfilActual().sesionActiva()) {
            this.setVisible(true);
            lblNombrePerfil.setText(PerfilActual.getPerfilActual().getNomreUsuario());
        } else {
            this.setVisible(false);
            Mensaje.getInstancia().error("Debes de iniciar sesión");
            InicioSesion.getInstancia().mostrarInicioSesion();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAcercaDe;
    private javax.swing.JLabel lblCalendarioCholqij;
    private javax.swing.JLabel lblCalendarioLunar;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblConvertidorDeFechas;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblFormasDeContar;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMenuPrincipal;
    private javax.swing.JLabel lblNombrePerfil;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblTiempoMaya;
    private javax.swing.JPanel panelBarraMenu;
    private javax.swing.JPanel panelPerfil;
    // End of variables declaration//GEN-END:variables
}
